# Dockerfile.prod
# Stage 1: Build dell'applicazione Next.js
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY . .
RUN npm run build
RUN npx prisma generate # Genera il client Prisma

# Stage 2: Immagine finale leggera per la produzione
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/public ./public

EXPOSE 3000
# Esegui le migrazioni e poi avvia l'applicazione
CMD ["sh", "-c", "npx prisma migrate deploy && npm start"]