# Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Installa le dipendenze del progetto
RUN npm ci

# Questo assicura che schema.prisma sia disponibile al percorso atteso.
COPY src ./src

RUN npx prisma generate