version: '3.8'

services:
  app:
    build: .
    container_name: grow-cms-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password@db:5432/grow-db?schema=public
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: grow-cms-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grow-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
